# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0002_img_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='superuser',
            name='sighs',
            field=models.IntegerField(default=0),
        ),
    ]
