# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0003_superuser_sighs'),
    ]

    operations = [
        migrations.AddField(
            model_name='superuser',
            name='date',
            field=models.IntegerField(default=0),
        ),
    ]
