# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0004_superuser_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superuser',
            name='sighs',
            field=models.IntegerField(default=1),
        ),
    ]
