# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0005_auto_20171128_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='superuser',
            name='cha',
            field=models.CharField(default='hllo', max_length=100),
        ),
    ]
