# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0006_superuser_cha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superuser',
            name='date',
            field=models.IntegerField(default=11),
        ),
    ]
