# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0007_auto_20171129_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superuser',
            name='sighs',
            field=models.IntegerField(default=0),
        ),
    ]
