# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0009_auto_20171129_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='img',
            field=models.FileField(null=True, upload_to='upload/'),
        ),
    ]
