# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0010_auto_20171129_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='superuser',
            name='touxiang',
            field=models.FileField(null=True, upload_to='upload/'),
        ),
    ]
