# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0011_superuser_touxiang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superuser',
            name='touxiang',
            field=models.FileField(null=True, upload_to='touxiang/'),
        ),
    ]
