# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0012_auto_20171130_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superuser',
            name='touxiang',
            field=models.FileField(blank=True, default='touxiang/moren.png', null=True, upload_to='touxiang/'),
        ),
    ]
