# Generated by Django 2.0.1 on 2018-01-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0020_auto_20180126_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dairy',
            name='diary_txt',
            field=models.CharField(default='hllo', max_length=100),
        ),
    ]
