# Generated by Django 2.0.1 on 2018-01-26 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0022_dairy1_dairy2_dairy3_dairy4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dairy1',
            old_name='diary_txt1',
            new_name='diary_txt',
        ),
        migrations.RenameField(
            model_name='dairy2',
            old_name='diary_txt2',
            new_name='diary_txt',
        ),
        migrations.RenameField(
            model_name='dairy3',
            old_name='diary_txt3',
            new_name='diary_txt',
        ),
        migrations.RenameField(
            model_name='dairy4',
            old_name='diary_txt4',
            new_name='diary_txt',
        ),
    ]
