# Generated by Django 2.0.1 on 2018-01-28 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0023_auto_20180126_1433'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dairy4',
            new_name='diary',
        ),
        migrations.RenameModel(
            old_name='dairy3',
            new_name='diary1',
        ),
        migrations.RenameModel(
            old_name='dairy1',
            new_name='diary2',
        ),
        migrations.RenameModel(
            old_name='dairy',
            new_name='diary3',
        ),
        migrations.RenameModel(
            old_name='dairy2',
            new_name='diary4',
        ),
    ]
