# Generated by Django 2.0.1 on 2018-01-28 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0024_auto_20180128_0530'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='hllo', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyBlog.diary2')),
            ],
        ),
    ]
