# Generated by Django 2.0.1 on 2018-01-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0027_auto_20180130_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment2',
            name='comment',
            field=models.CharField(default='hllo', max_length=100),
        ),
    ]
