# Generated by Django 2.0.1 on 2018-01-30 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0028_auto_20180130_1441'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comment2',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='diary1',
            name='user',
        ),
        migrations.RemoveField(
            model_name='diary2',
            name='user',
        ),
        migrations.RemoveField(
            model_name='diary3',
            name='user',
        ),
        migrations.RemoveField(
            model_name='diary4',
            name='user',
        ),
        migrations.AddField(
            model_name='diary',
            name='kind',
            field=models.CharField(default='hllo', max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyBlog.diary'),
        ),
        migrations.DeleteModel(
            name='diary1',
        ),
        migrations.DeleteModel(
            name='diary2',
        ),
        migrations.DeleteModel(
            name='diary3',
        ),
        migrations.DeleteModel(
            name='diary4',
        ),
    ]
