# Generated by Django 2.0.1 on 2018-01-30 16:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0030_diary_url_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='title',
            field=tinymce.models.HTMLField(default='hllo', max_length=100),
        ),
    ]
