# Generated by Django 2.0.1 on 2018-01-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0031_diary_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='title',
            field=models.CharField(default='hllo', max_length=100),
        ),
    ]
