# Generated by Django 2.0.1 on 2018-01-30 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0032_auto_20180130_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='url_slug',
            new_name='slug',
        ),
    ]
