# Generated by Django 2.0.1 on 2018-01-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0033_auto_20180130_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
